dist: xenial
services:
  - docker

jobs:
  include:
    - stage: lint
      script:
        - bash test/linters.sh
    - stage: test
      script:
        - bash test/setup.sh
        - ./test/bats/bin/bats test/tests.bats
        - bash test/clean.sh
