language: shell
dist: xenial
services:
  - docker

install:
  - curl -sL -o $HOME/hadolint https://github.com/hadolint/hadolint/releases/download/v1.17.3/hadolint-Linux-x86_64 && chmod 755 $HOME/hadolint

script:
  - bash test/linters.sh
  - bash test/setup.sh
  - ./test/bats/bin/bats test/tests.bats
  - bash test/clean.sh

after_success:
  - echo $DOCKER_PASS | docker login -u selfhostingtools --password-stdin
  - docker push selfhostingtools/nsd-docker:latest
